// Code generated by protoc-gen-go. DO NOT EDIT.
// source: authCenter.proto

package go_micro_srv_authCenter

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type VerifyWechatCodeRequest struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyWechatCodeRequest) Reset()         { *m = VerifyWechatCodeRequest{} }
func (m *VerifyWechatCodeRequest) String() string { return proto.CompactTextString(m) }
func (*VerifyWechatCodeRequest) ProtoMessage()    {}
func (*VerifyWechatCodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_authCenter_cdc7fe5bf15ed5be, []int{0}
}
func (m *VerifyWechatCodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyWechatCodeRequest.Unmarshal(m, b)
}
func (m *VerifyWechatCodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyWechatCodeRequest.Marshal(b, m, deterministic)
}
func (dst *VerifyWechatCodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyWechatCodeRequest.Merge(dst, src)
}
func (m *VerifyWechatCodeRequest) XXX_Size() int {
	return xxx_messageInfo_VerifyWechatCodeRequest.Size(m)
}
func (m *VerifyWechatCodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyWechatCodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyWechatCodeRequest proto.InternalMessageInfo

func (m *VerifyWechatCodeRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type VerifyWechatCodeResponse struct {
	OpenID               string   `protobuf:"bytes,1,opt,name=openID" json:"openID,omitempty"`
	SessionKey           string   `protobuf:"bytes,2,opt,name=sessionKey" json:"sessionKey,omitempty"`
	UnionID              string   `protobuf:"bytes,3,opt,name=unionID" json:"unionID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyWechatCodeResponse) Reset()         { *m = VerifyWechatCodeResponse{} }
func (m *VerifyWechatCodeResponse) String() string { return proto.CompactTextString(m) }
func (*VerifyWechatCodeResponse) ProtoMessage()    {}
func (*VerifyWechatCodeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_authCenter_cdc7fe5bf15ed5be, []int{1}
}
func (m *VerifyWechatCodeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyWechatCodeResponse.Unmarshal(m, b)
}
func (m *VerifyWechatCodeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyWechatCodeResponse.Marshal(b, m, deterministic)
}
func (dst *VerifyWechatCodeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyWechatCodeResponse.Merge(dst, src)
}
func (m *VerifyWechatCodeResponse) XXX_Size() int {
	return xxx_messageInfo_VerifyWechatCodeResponse.Size(m)
}
func (m *VerifyWechatCodeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyWechatCodeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyWechatCodeResponse proto.InternalMessageInfo

func (m *VerifyWechatCodeResponse) GetOpenID() string {
	if m != nil {
		return m.OpenID
	}
	return ""
}

func (m *VerifyWechatCodeResponse) GetSessionKey() string {
	if m != nil {
		return m.SessionKey
	}
	return ""
}

func (m *VerifyWechatCodeResponse) GetUnionID() string {
	if m != nil {
		return m.UnionID
	}
	return ""
}

type GetTokensRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTokensRequest) Reset()         { *m = GetTokensRequest{} }
func (m *GetTokensRequest) String() string { return proto.CompactTextString(m) }
func (*GetTokensRequest) ProtoMessage()    {}
func (*GetTokensRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_authCenter_cdc7fe5bf15ed5be, []int{2}
}
func (m *GetTokensRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTokensRequest.Unmarshal(m, b)
}
func (m *GetTokensRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTokensRequest.Marshal(b, m, deterministic)
}
func (dst *GetTokensRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTokensRequest.Merge(dst, src)
}
func (m *GetTokensRequest) XXX_Size() int {
	return xxx_messageInfo_GetTokensRequest.Size(m)
}
func (m *GetTokensRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTokensRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTokensRequest proto.InternalMessageInfo

func (m *GetTokensRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type GetTokensResponse struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=accessToken" json:"accessToken,omitempty"`
	RefreshToken         string   `protobuf:"bytes,2,opt,name=refreshToken" json:"refreshToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTokensResponse) Reset()         { *m = GetTokensResponse{} }
func (m *GetTokensResponse) String() string { return proto.CompactTextString(m) }
func (*GetTokensResponse) ProtoMessage()    {}
func (*GetTokensResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_authCenter_cdc7fe5bf15ed5be, []int{3}
}
func (m *GetTokensResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTokensResponse.Unmarshal(m, b)
}
func (m *GetTokensResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTokensResponse.Marshal(b, m, deterministic)
}
func (dst *GetTokensResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTokensResponse.Merge(dst, src)
}
func (m *GetTokensResponse) XXX_Size() int {
	return xxx_messageInfo_GetTokensResponse.Size(m)
}
func (m *GetTokensResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTokensResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTokensResponse proto.InternalMessageInfo

func (m *GetTokensResponse) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *GetTokensResponse) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

type RefreshJWTRequest struct {
	RefreshToken         string   `protobuf:"bytes,1,opt,name=refreshToken" json:"refreshToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefreshJWTRequest) Reset()         { *m = RefreshJWTRequest{} }
func (m *RefreshJWTRequest) String() string { return proto.CompactTextString(m) }
func (*RefreshJWTRequest) ProtoMessage()    {}
func (*RefreshJWTRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_authCenter_cdc7fe5bf15ed5be, []int{4}
}
func (m *RefreshJWTRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshJWTRequest.Unmarshal(m, b)
}
func (m *RefreshJWTRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshJWTRequest.Marshal(b, m, deterministic)
}
func (dst *RefreshJWTRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshJWTRequest.Merge(dst, src)
}
func (m *RefreshJWTRequest) XXX_Size() int {
	return xxx_messageInfo_RefreshJWTRequest.Size(m)
}
func (m *RefreshJWTRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshJWTRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshJWTRequest proto.InternalMessageInfo

func (m *RefreshJWTRequest) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

type RefreshJWTResponse struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=accessToken" json:"accessToken,omitempty"`
	RefreshToken         string   `protobuf:"bytes,2,opt,name=refreshToken" json:"refreshToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefreshJWTResponse) Reset()         { *m = RefreshJWTResponse{} }
func (m *RefreshJWTResponse) String() string { return proto.CompactTextString(m) }
func (*RefreshJWTResponse) ProtoMessage()    {}
func (*RefreshJWTResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_authCenter_cdc7fe5bf15ed5be, []int{5}
}
func (m *RefreshJWTResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshJWTResponse.Unmarshal(m, b)
}
func (m *RefreshJWTResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshJWTResponse.Marshal(b, m, deterministic)
}
func (dst *RefreshJWTResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshJWTResponse.Merge(dst, src)
}
func (m *RefreshJWTResponse) XXX_Size() int {
	return xxx_messageInfo_RefreshJWTResponse.Size(m)
}
func (m *RefreshJWTResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshJWTResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshJWTResponse proto.InternalMessageInfo

func (m *RefreshJWTResponse) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *RefreshJWTResponse) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

func init() {
	proto.RegisterType((*VerifyWechatCodeRequest)(nil), "go.micro.srv.authCenter.VerifyWechatCodeRequest")
	proto.RegisterType((*VerifyWechatCodeResponse)(nil), "go.micro.srv.authCenter.VerifyWechatCodeResponse")
	proto.RegisterType((*GetTokensRequest)(nil), "go.micro.srv.authCenter.GetTokensRequest")
	proto.RegisterType((*GetTokensResponse)(nil), "go.micro.srv.authCenter.GetTokensResponse")
	proto.RegisterType((*RefreshJWTRequest)(nil), "go.micro.srv.authCenter.RefreshJWTRequest")
	proto.RegisterType((*RefreshJWTResponse)(nil), "go.micro.srv.authCenter.RefreshJWTResponse")
}

func init() { proto.RegisterFile("authCenter.proto", fileDescriptor_authCenter_cdc7fe5bf15ed5be) }

var fileDescriptor_authCenter_cdc7fe5bf15ed5be = []byte{
	// 325 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x53, 0x4d, 0x4f, 0xc2, 0x40,
	0x10, 0x15, 0x34, 0x18, 0x47, 0xa3, 0x30, 0x07, 0x68, 0x38, 0x18, 0xb2, 0x27, 0xc5, 0xb8, 0xf1,
	0xe3, 0xe0, 0xd9, 0x60, 0x42, 0xd4, 0x1b, 0x21, 0x12, 0xbd, 0xd5, 0x32, 0x48, 0x23, 0xee, 0xe2,
	0xce, 0xd6, 0x84, 0x7f, 0xeb, 0x4f, 0x31, 0x76, 0x5b, 0x5a, 0x8b, 0x4d, 0x30, 0xf1, 0xd6, 0x79,
	0xf3, 0xde, 0xcc, 0xeb, 0xbc, 0x2c, 0xd4, 0xfd, 0xc8, 0x4e, 0x7b, 0xa4, 0x2c, 0x19, 0x39, 0x37,
	0xda, 0x6a, 0x6c, 0xbd, 0x68, 0xf9, 0x16, 0x06, 0x46, 0x4b, 0x36, 0x1f, 0x32, 0x6b, 0x8b, 0x53,
	0x68, 0x3d, 0x90, 0x09, 0x27, 0x8b, 0x11, 0x05, 0x53, 0xdf, 0xf6, 0xf4, 0x98, 0x06, 0xf4, 0x1e,
	0x11, 0x5b, 0x44, 0xd8, 0x0a, 0xf4, 0x98, 0xbc, 0x4a, 0xa7, 0x72, 0xb4, 0x33, 0x88, 0xbf, 0xc5,
	0x0c, 0xbc, 0x55, 0x3a, 0xcf, 0xb5, 0x62, 0xc2, 0x26, 0xd4, 0xf4, 0x9c, 0xd4, 0xed, 0x4d, 0xa2,
	0x48, 0x2a, 0x3c, 0x04, 0x60, 0x62, 0x0e, 0xb5, 0xba, 0xa7, 0x85, 0x57, 0x8d, 0x7b, 0x39, 0x04,
	0x3d, 0xd8, 0x8e, 0x54, 0xa8, 0xbf, 0x85, 0x9b, 0x71, 0x33, 0x2d, 0x45, 0x17, 0xea, 0x7d, 0xb2,
	0x43, 0xfd, 0x4a, 0x8a, 0x53, 0x57, 0x4d, 0xa8, 0x45, 0x4c, 0x26, 0xdb, 0xe2, 0x2a, 0xf1, 0x08,
	0x8d, 0x1c, 0x37, 0xb1, 0xd4, 0x81, 0x5d, 0x3f, 0x08, 0x88, 0x39, 0xc6, 0x13, 0x45, 0x1e, 0x42,
	0x01, 0x7b, 0x86, 0x26, 0x86, 0x78, 0xea, 0x28, 0xce, 0xde, 0x0f, 0x4c, 0x5c, 0x41, 0x63, 0xe0,
	0xea, 0xbb, 0xd1, 0x30, 0xf5, 0x51, 0x14, 0x56, 0x7e, 0x11, 0x3e, 0x01, 0xe6, 0x85, 0xff, 0x69,
	0xea, 0xe2, 0xb3, 0x0a, 0x70, 0xbd, 0xcc, 0x11, 0x17, 0x50, 0x2f, 0x06, 0x83, 0x67, 0xb2, 0x24,
	0x75, 0x59, 0x12, 0x79, 0xfb, 0xfc, 0x0f, 0x0a, 0xf7, 0x37, 0x62, 0x03, 0x43, 0xd8, 0xef, 0x93,
	0x22, 0xe3, 0x5b, 0x72, 0xe7, 0xc7, 0xe3, 0xd2, 0x31, 0xc5, 0x38, 0xdb, 0xdd, 0x75, 0xa8, 0xcb,
	0x55, 0x33, 0x38, 0xc8, 0x0e, 0xea, 0x6e, 0x55, 0x3e, 0x60, 0x25, 0xb3, 0xf6, 0xc9, 0x5a, 0xdc,
	0x74, 0xdb, 0x73, 0x2d, 0x7e, 0x3b, 0x97, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xe8, 0x76, 0xf1,
	0xd7, 0x4f, 0x03, 0x00, 0x00,
}
