// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: authCenter.proto

/*
Package go_micro_srv_authCenter is a generated protocol buffer package.

It is generated from these files:
	authCenter.proto

It has these top-level messages:
	VerifyWechatCodeRequest
	VerifyWechatCodeResponse
	GetTokensRequest
	GetTokensResponse
	RefreshJWTRequest
	RefreshJWTResponse
*/
package go_micro_srv_authCenter

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for AuthCenter service

type AuthCenterService interface {
	VerifyWechatCode(ctx context.Context, in *VerifyWechatCodeRequest, opts ...client.CallOption) (*VerifyWechatCodeResponse, error)
	GenerateTokens(ctx context.Context, in *GetTokensRequest, opts ...client.CallOption) (*GetTokensResponse, error)
	RefreshJWTToken(ctx context.Context, in *RefreshJWTRequest, opts ...client.CallOption) (*RefreshJWTResponse, error)
}

type authCenterService struct {
	c    client.Client
	name string
}

func NewAuthCenterService(name string, c client.Client) AuthCenterService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "go.micro.srv.authCenter"
	}
	return &authCenterService{
		c:    c,
		name: name,
	}
}

func (c *authCenterService) VerifyWechatCode(ctx context.Context, in *VerifyWechatCodeRequest, opts ...client.CallOption) (*VerifyWechatCodeResponse, error) {
	req := c.c.NewRequest(c.name, "AuthCenter.VerifyWechatCode", in)
	out := new(VerifyWechatCodeResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authCenterService) GenerateTokens(ctx context.Context, in *GetTokensRequest, opts ...client.CallOption) (*GetTokensResponse, error) {
	req := c.c.NewRequest(c.name, "AuthCenter.GenerateTokens", in)
	out := new(GetTokensResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authCenterService) RefreshJWTToken(ctx context.Context, in *RefreshJWTRequest, opts ...client.CallOption) (*RefreshJWTResponse, error) {
	req := c.c.NewRequest(c.name, "AuthCenter.RefreshJWTToken", in)
	out := new(RefreshJWTResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AuthCenter service

type AuthCenterHandler interface {
	VerifyWechatCode(context.Context, *VerifyWechatCodeRequest, *VerifyWechatCodeResponse) error
	GenerateTokens(context.Context, *GetTokensRequest, *GetTokensResponse) error
	RefreshJWTToken(context.Context, *RefreshJWTRequest, *RefreshJWTResponse) error
}

func RegisterAuthCenterHandler(s server.Server, hdlr AuthCenterHandler, opts ...server.HandlerOption) error {
	type authCenter interface {
		VerifyWechatCode(ctx context.Context, in *VerifyWechatCodeRequest, out *VerifyWechatCodeResponse) error
		GenerateTokens(ctx context.Context, in *GetTokensRequest, out *GetTokensResponse) error
		RefreshJWTToken(ctx context.Context, in *RefreshJWTRequest, out *RefreshJWTResponse) error
	}
	type AuthCenter struct {
		authCenter
	}
	h := &authCenterHandler{hdlr}
	return s.Handle(s.NewHandler(&AuthCenter{h}, opts...))
}

type authCenterHandler struct {
	AuthCenterHandler
}

func (h *authCenterHandler) VerifyWechatCode(ctx context.Context, in *VerifyWechatCodeRequest, out *VerifyWechatCodeResponse) error {
	return h.AuthCenterHandler.VerifyWechatCode(ctx, in, out)
}

func (h *authCenterHandler) GenerateTokens(ctx context.Context, in *GetTokensRequest, out *GetTokensResponse) error {
	return h.AuthCenterHandler.GenerateTokens(ctx, in, out)
}

func (h *authCenterHandler) RefreshJWTToken(ctx context.Context, in *RefreshJWTRequest, out *RefreshJWTResponse) error {
	return h.AuthCenterHandler.RefreshJWTToken(ctx, in, out)
}
