// Code generated by protoc-gen-go. DO NOT EDIT.
// source: authCenter.proto

package go_micro_srv_authCenter

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type VerifyWechatCodeRequest struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyWechatCodeRequest) Reset()         { *m = VerifyWechatCodeRequest{} }
func (m *VerifyWechatCodeRequest) String() string { return proto.CompactTextString(m) }
func (*VerifyWechatCodeRequest) ProtoMessage()    {}
func (*VerifyWechatCodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c7c094d932880046, []int{0}
}

func (m *VerifyWechatCodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyWechatCodeRequest.Unmarshal(m, b)
}
func (m *VerifyWechatCodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyWechatCodeRequest.Marshal(b, m, deterministic)
}
func (m *VerifyWechatCodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyWechatCodeRequest.Merge(m, src)
}
func (m *VerifyWechatCodeRequest) XXX_Size() int {
	return xxx_messageInfo_VerifyWechatCodeRequest.Size(m)
}
func (m *VerifyWechatCodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyWechatCodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyWechatCodeRequest proto.InternalMessageInfo

func (m *VerifyWechatCodeRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type VerifyWechatCodeResponse struct {
	OpenID               string   `protobuf:"bytes,1,opt,name=openID,proto3" json:"openID,omitempty"`
	SessionKey           string   `protobuf:"bytes,2,opt,name=sessionKey,proto3" json:"sessionKey,omitempty"`
	UnionID              string   `protobuf:"bytes,3,opt,name=unionID,proto3" json:"unionID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyWechatCodeResponse) Reset()         { *m = VerifyWechatCodeResponse{} }
func (m *VerifyWechatCodeResponse) String() string { return proto.CompactTextString(m) }
func (*VerifyWechatCodeResponse) ProtoMessage()    {}
func (*VerifyWechatCodeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c7c094d932880046, []int{1}
}

func (m *VerifyWechatCodeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyWechatCodeResponse.Unmarshal(m, b)
}
func (m *VerifyWechatCodeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyWechatCodeResponse.Marshal(b, m, deterministic)
}
func (m *VerifyWechatCodeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyWechatCodeResponse.Merge(m, src)
}
func (m *VerifyWechatCodeResponse) XXX_Size() int {
	return xxx_messageInfo_VerifyWechatCodeResponse.Size(m)
}
func (m *VerifyWechatCodeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyWechatCodeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyWechatCodeResponse proto.InternalMessageInfo

func (m *VerifyWechatCodeResponse) GetOpenID() string {
	if m != nil {
		return m.OpenID
	}
	return ""
}

func (m *VerifyWechatCodeResponse) GetSessionKey() string {
	if m != nil {
		return m.SessionKey
	}
	return ""
}

func (m *VerifyWechatCodeResponse) GetUnionID() string {
	if m != nil {
		return m.UnionID
	}
	return ""
}

type GetJWTTokenRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetJWTTokenRequest) Reset()         { *m = GetJWTTokenRequest{} }
func (m *GetJWTTokenRequest) String() string { return proto.CompactTextString(m) }
func (*GetJWTTokenRequest) ProtoMessage()    {}
func (*GetJWTTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c7c094d932880046, []int{2}
}

func (m *GetJWTTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetJWTTokenRequest.Unmarshal(m, b)
}
func (m *GetJWTTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetJWTTokenRequest.Marshal(b, m, deterministic)
}
func (m *GetJWTTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetJWTTokenRequest.Merge(m, src)
}
func (m *GetJWTTokenRequest) XXX_Size() int {
	return xxx_messageInfo_GetJWTTokenRequest.Size(m)
}
func (m *GetJWTTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetJWTTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetJWTTokenRequest proto.InternalMessageInfo

func (m *GetJWTTokenRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type GetJWTTokenResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetJWTTokenResponse) Reset()         { *m = GetJWTTokenResponse{} }
func (m *GetJWTTokenResponse) String() string { return proto.CompactTextString(m) }
func (*GetJWTTokenResponse) ProtoMessage()    {}
func (*GetJWTTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c7c094d932880046, []int{3}
}

func (m *GetJWTTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetJWTTokenResponse.Unmarshal(m, b)
}
func (m *GetJWTTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetJWTTokenResponse.Marshal(b, m, deterministic)
}
func (m *GetJWTTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetJWTTokenResponse.Merge(m, src)
}
func (m *GetJWTTokenResponse) XXX_Size() int {
	return xxx_messageInfo_GetJWTTokenResponse.Size(m)
}
func (m *GetJWTTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetJWTTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetJWTTokenResponse proto.InternalMessageInfo

func (m *GetJWTTokenResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterType((*VerifyWechatCodeRequest)(nil), "go.micro.srv.authCenter.VerifyWechatCodeRequest")
	proto.RegisterType((*VerifyWechatCodeResponse)(nil), "go.micro.srv.authCenter.VerifyWechatCodeResponse")
	proto.RegisterType((*GetJWTTokenRequest)(nil), "go.micro.srv.authCenter.GetJWTTokenRequest")
	proto.RegisterType((*GetJWTTokenResponse)(nil), "go.micro.srv.authCenter.GetJWTTokenResponse")
}

func init() { proto.RegisterFile("authCenter.proto", fileDescriptor_c7c094d932880046) }

var fileDescriptor_c7c094d932880046 = []byte{
	// 263 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0xcb, 0x4a, 0x03, 0x41,
	0x10, 0x74, 0x7d, 0xac, 0x58, 0x5e, 0x42, 0x2b, 0xc9, 0x92, 0x83, 0xc8, 0x9c, 0x84, 0xc4, 0xc1,
	0xc7, 0x17, 0x48, 0x04, 0x51, 0x6f, 0x21, 0x98, 0x73, 0xdc, 0xb4, 0x66, 0x7d, 0x4c, 0xaf, 0x33,
	0xb3, 0xc2, 0x7e, 0xb7, 0x3f, 0x20, 0xd9, 0x87, 0x89, 0x86, 0x05, 0x73, 0x9b, 0xea, 0xaa, 0x9a,
	0xae, 0x29, 0x06, 0xad, 0x49, 0xe6, 0x67, 0x03, 0x36, 0x9e, 0xad, 0x4e, 0xad, 0x78, 0xa1, 0xce,
	0xb3, 0xe8, 0xf7, 0x24, 0xb6, 0xa2, 0x9d, 0xfd, 0xd4, 0x0b, 0x5a, 0x9d, 0xa2, 0xf3, 0xc0, 0x36,
	0x79, 0xca, 0xc7, 0x1c, 0xcf, 0x26, 0x7e, 0x20, 0x53, 0x1e, 0xf2, 0x47, 0xc6, 0xce, 0x13, 0x61,
	0x3b, 0x96, 0x29, 0x47, 0xc1, 0x71, 0x70, 0xb2, 0x37, 0x2c, 0xce, 0xea, 0x0d, 0xd1, 0xaa, 0xdc,
	0xa5, 0x62, 0x1c, 0x53, 0x1b, 0xa1, 0xa4, 0x6c, 0x6e, 0xaf, 0x2b, 0x47, 0x85, 0xe8, 0x08, 0x70,
	0xec, 0x5c, 0x22, 0xe6, 0x9e, 0xf3, 0x68, 0xb3, 0xe0, 0x96, 0x26, 0x14, 0x61, 0x37, 0x33, 0x89,
	0xcc, 0x8d, 0x5b, 0x05, 0x59, 0x43, 0xd5, 0x07, 0xdd, 0xb0, 0xbf, 0x1b, 0x8f, 0x46, 0xf2, 0xca,
	0xa6, 0xce, 0xd5, 0x46, 0x98, 0x39, 0xb6, 0x8b, 0x3d, 0x25, 0x52, 0x3d, 0x1c, 0xfc, 0x52, 0x57,
	0xb1, 0x0e, 0xb1, 0xe3, 0xe7, 0x83, 0x4a, 0x5d, 0x82, 0x8b, 0xaf, 0x00, 0xb8, 0xfa, 0xa9, 0x81,
	0x72, 0xb4, 0xfe, 0xbe, 0x8b, 0xce, 0x74, 0x43, 0x69, 0xba, 0xa1, 0xb1, 0xee, 0xf9, 0x1a, 0x8e,
	0x32, 0x9d, 0xda, 0xa0, 0x17, 0xec, 0x2f, 0xc5, 0xa6, 0x5e, 0xe3, 0x1d, 0xab, 0x55, 0x74, 0xfb,
	0xff, 0x13, 0xd7, 0xbb, 0x1e, 0xc3, 0xe2, 0x37, 0x5c, 0x7e, 0x07, 0x00, 0x00, 0xff, 0xff, 0x68,
	0xe1, 0xb5, 0x8f, 0x21, 0x02, 0x00, 0x00,
}
