// Code generated by protoc-gen-go. DO NOT EDIT.
// source: authCenter.proto

package go_micro_srv_authCenter

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type VerifyWechatCodeRequest struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyWechatCodeRequest) Reset()         { *m = VerifyWechatCodeRequest{} }
func (m *VerifyWechatCodeRequest) String() string { return proto.CompactTextString(m) }
func (*VerifyWechatCodeRequest) ProtoMessage()    {}
func (*VerifyWechatCodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c7c094d932880046, []int{0}
}

func (m *VerifyWechatCodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyWechatCodeRequest.Unmarshal(m, b)
}
func (m *VerifyWechatCodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyWechatCodeRequest.Marshal(b, m, deterministic)
}
func (m *VerifyWechatCodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyWechatCodeRequest.Merge(m, src)
}
func (m *VerifyWechatCodeRequest) XXX_Size() int {
	return xxx_messageInfo_VerifyWechatCodeRequest.Size(m)
}
func (m *VerifyWechatCodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyWechatCodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyWechatCodeRequest proto.InternalMessageInfo

func (m *VerifyWechatCodeRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type VerifyWechatCodeResponse struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyWechatCodeResponse) Reset()         { *m = VerifyWechatCodeResponse{} }
func (m *VerifyWechatCodeResponse) String() string { return proto.CompactTextString(m) }
func (*VerifyWechatCodeResponse) ProtoMessage()    {}
func (*VerifyWechatCodeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c7c094d932880046, []int{1}
}

func (m *VerifyWechatCodeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyWechatCodeResponse.Unmarshal(m, b)
}
func (m *VerifyWechatCodeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyWechatCodeResponse.Marshal(b, m, deterministic)
}
func (m *VerifyWechatCodeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyWechatCodeResponse.Merge(m, src)
}
func (m *VerifyWechatCodeResponse) XXX_Size() int {
	return xxx_messageInfo_VerifyWechatCodeResponse.Size(m)
}
func (m *VerifyWechatCodeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyWechatCodeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyWechatCodeResponse proto.InternalMessageInfo

func (m *VerifyWechatCodeResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*VerifyWechatCodeRequest)(nil), "go.micro.srv.authCenter.VerifyWechatCodeRequest")
	proto.RegisterType((*VerifyWechatCodeResponse)(nil), "go.micro.srv.authCenter.VerifyWechatCodeResponse")
}

func init() { proto.RegisterFile("authCenter.proto", fileDescriptor_c7c094d932880046) }

var fileDescriptor_c7c094d932880046 = []byte{
	// 163 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x48, 0x2c, 0x2d, 0xc9,
	0x70, 0x4e, 0xcd, 0x2b, 0x49, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x4f, 0xcf,
	0xd7, 0xcb, 0xcd, 0x4c, 0x2e, 0xca, 0xd7, 0x2b, 0x2e, 0x2a, 0xd3, 0x43, 0x48, 0x2b, 0xe9, 0x72,
	0x89, 0x87, 0xa5, 0x16, 0x65, 0xa6, 0x55, 0x86, 0xa7, 0x26, 0x67, 0x24, 0x96, 0x38, 0xe7, 0xa7,
	0xa4, 0x06, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08, 0x09, 0x71, 0xb1, 0x24, 0xe7, 0xa7, 0xa4,
	0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x81, 0xd9, 0x4a, 0x3a, 0x5c, 0x12, 0x98, 0xca, 0x8b,
	0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x85, 0x04, 0xb8, 0x98, 0x73, 0x8b, 0xd3, 0xa1, 0xca, 0x41, 0x4c,
	0xa3, 0x76, 0x46, 0x2e, 0x2e, 0x47, 0xb8, 0x5d, 0x42, 0x95, 0x5c, 0x02, 0xe8, 0x9a, 0x85, 0x0c,
	0xf4, 0x70, 0xb8, 0x4c, 0x0f, 0x87, 0xb3, 0xa4, 0x0c, 0x49, 0xd0, 0x01, 0x71, 0x99, 0x12, 0x43,
	0x12, 0x1b, 0x38, 0x18, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x66, 0x05, 0x2b, 0xae, 0x1a,
	0x01, 0x00, 0x00,
}
